version: 2
updates:
- package-ecosystem: npm
  directory: "/WorkflowEngine"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: fastify
    versions:
    - 3.10.1
    - 3.11.0
    - 3.12.0
    - 3.13.0
    - 3.14.0
    - 3.14.1
    - 3.14.2
  - dependency-name: mongoose
    versions:
    - 5.11.13
    - 5.11.14
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
  - dependency-name: pino
    versions:
    - 6.11.0
    - 6.11.1
    - 6.11.2
  - dependency-name: pino-pretty
    versions:
    - 4.3.0
    - 4.4.0
    - 4.5.0
    - 4.7.0
  - dependency-name: fastify-sensible
    versions:
    - 3.1.0
- package-ecosystem: npm
  directory: "/WorkflowEncoder"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: pino
    versions:
    - 6.11.0
    - 6.11.1
    - 6.11.2
  - dependency-name: pino-pretty
    versions:
    - 4.3.0
    - 4.4.0
    - 4.5.0
    - 4.7.0
